
services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-latest}
    container_name: jira_postgres
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - jira_postgres_data:/var/lib/postgresql/data
    networks:
      - jira_network

  jira:
    image: atlassian/jira-software:${JIRA_VERSION:-latest}
    container_name: jira
    restart: unless-stopped
    ports:
      - "${HOST_PORT}:8080"
    environment:
      ATL_JDBC_URL: jdbc:postgresql://postgres:5432/jiradb
      ATL_JDBC_USER: ${POSTGRES_USER}
      ATL_JDBC_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    volumes:
      - jira_data:/var/atlassian/application-data/jira
    networks:
      - jira_network

volumes:
  jira_postgres_data:
  jira_data:

networks:
  jira_network:
    driver: bridge
